#!/bin/sh
set -x

switch=br0

if [ -n "$1" ];then
        #tunctl -u `whoami` -t $1
        ip link add name $switch type bridge
	ip link set $switch up
	ip link set $1 master $switch
        ip tuntap add $1 mode tap user `whoami`
        ip link set $1 up
        sleep 0.5s
        #brctl addif $switch $1
        ip link set $1 master $switch
	dhclient -r
	dhclient
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi
